# Generated by Django 5.0.1 on 2024-02-13 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dva', '0003_alter_virtualaccount_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualaccount',
            name='bank',
        ),
        migrations.AlterField(
            model_name='virtualaccount',
            name='customer_id',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator(message='Customer ID should be 11 digits', regex='^\\d{11}$')]),
        ),
    ]
