# Generated by Django 5.0.1 on 2024-02-13 12:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dva', '0004_remove_virtualaccount_bank_and_more'),
        ('listofsupportedbanks', '0002_alter_supportedbank_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualaccount',
            name='bank',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='listofsupportedbanks.supportedbank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='virtualaccount',
            name='customer_id',
            field=models.CharField(default='', max_length=11),
        ),
    ]
