# Generated by Django 5.0.1 on 2024-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listofsupportedbanks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportedbank',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supportedbank',
            name='local_reference',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supportedbank',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
