# Generated by Django 5.0.1 on 2024-02-01 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpass', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpasswordrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='forgotpasswordrequest',
            name='email',
        ),
        migrations.AddField(
            model_name='forgotpasswordrequest',
            name='encrypted_token',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='forgotpasswordrequest',
            name='encrypted_token_iv',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='forgotpasswordrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
