# Generated by Django 5.0.1 on 2024-02-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forpass', '0003_forgot_delete_forgotpasswordrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgot',
            old_name='password_reset_token',
            new_name='reset_token',
        ),
    ]
