# Generated by Django 5.0.1 on 2024-02-06 07:39

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +234XXXXXXXXXX.', regex='^\\+?234?\\d{10}$')], verbose_name='Phone Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='Password')),
                ('gender', models.CharField(blank=True, choices=[(1, 'Male'), (2, 'Female')], max_length=10, null=True)),
                ('residential_address', models.TextField(blank=True, verbose_name='Residential Address')),
                ('referral_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referral Code')),
                ('wallet_address', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='rent_customappuser_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_app_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
