# Generated by Django 5.0.1 on 2024-01-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BVNVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvn', models.CharField(max_length=11, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
