# Generated by Django 5.0.1 on 2024-02-13 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0003_remove_passwordreset_hashed_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
