# Generated by Django 5.0.1 on 2024-02-13 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0004_passwordreset_email_passwordreset_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='new_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='old_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
