# Generated by Django 5.0.1 on 2024-02-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0005_passwordreset_new_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='new_password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='old_password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
