# Generated by Django 5.0.1 on 2024-02-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='encrypted_field',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='encrypted_field_iv',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='end_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='start_date',
            field=models.DateField(default=''),
        ),
    ]
