# Generated by Django 5.0.1 on 2024-02-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question',
        ),
        migrations.AddField(
            model_name='faq',
            name='encrypted_answer',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='faq',
            name='encrypted_question',
            field=models.BinaryField(default=b''),
        ),
    ]
