# Generated by Django 5.0.1 on 2024-02-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='encrypted_otp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(default='3f77ed', max_length=6),
        ),
    ]
