# Generated by Django 5.0.1 on 2024-02-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_otp_encrypted_otp_otp_expiration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(default='338036', max_length=6),
        ),
    ]
