# Generated by Django 5.0.1 on 2024-02-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_options_rename_user_wallet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
    ]
