# Generated by Django 5.0.1 on 2024-02-06 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='rent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.user'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='user_identifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_user', to='rent.user'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_account_accountuser_user_permissions', to='auth.permission'),
        ),
    ]
