# Generated by Django 5.0.1 on 2024-02-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceRentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('savings_interval', models.CharField(max_length=100)),
                ('encrypted_data', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Space Rent Profiles',
            },
        ),
    ]
