# Generated by Django 5.0.1 on 2024-02-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_aes_key_notification_jwt_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='aes_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='jwt_token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
