# Generated by Django 5.0.1 on 2024-02-01 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pverification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
