# Generated by Django 5.0.1 on 2024-02-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pverification', '0002_phoneverification_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneverification',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='encrypted_verification_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
