# Generated by Django 5.0.1 on 2024-01-28 18:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bdebit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvndebituser',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bvndebituser',
            name='charge_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bvndebituser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='bdebit_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='bvndebituser',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bvndebituser',
            name='transaction_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bvndebituser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='bdebit_user_permissions', to='auth.permission'),
        ),
    ]
